
[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "GrUZEe4fs4dWW4bm9xGe9YuTJT2xESx29BksT1AX6ueM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "target/deploy/anchor_counter-keypair.json"

[scripts]
test = "cd programs/anchor-counter && cargo test"
