
[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "7rYmEqGjsw9UirDgHfQn1zCzwZRU5uSfLK19fSqzM7uF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cd programs/anchor-counter && cargo test"
