cargo-features = ["edition2024"]

[package]
name = "native-vault"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]
name = "native_vault"

[dependencies]
pinocchio = "0.9.0"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.3.0"

[dev-dependencies]
borsh = {version = "1.5.7", features = ["derive"]}
mollusk-svm = "0.4.1"
solana-account = "2.2.1"
solana-instruction = "2.3.0"
solana-pubkey = "2.4.0"
