[package]
name = "voting"
version = "0.1.0"
description = "Using Pinocchio"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "voting"

[dependencies]
pinocchio = "0.8.4"
pinocchio-log = "0.4.0"
borsh = { version = "=1.5.7", features = ["derive"] }

[dev-dependencies]
mollusk-svm = "0.4.1"
solana-program-test = "2.3.3"
solana-account = "2.2.1"
solana-instruction = "2.2.1"
solana-pubkey = "2.2.1"